//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExMyStudy
{
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(3)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class EnWordsFormat : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrWORD1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrWORD2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrWORD3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrWORD4;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPRON1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPRON2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPRON3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPRON4;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrMEAN1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrMEAN2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrMEAN3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrMEAN4;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public EnWordsFormat(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet3", "Sheet3") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.EnWordsFormat = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.nrWORD1.BeginInit();
            this.nrWORD2.BeginInit();
            this.nrWORD3.BeginInit();
            this.nrWORD4.BeginInit();
            this.nrPRON1.BeginInit();
            this.nrPRON2.BeginInit();
            this.nrPRON3.BeginInit();
            this.nrPRON4.BeginInit();
            this.nrMEAN1.BeginInit();
            this.nrMEAN2.BeginInit();
            this.nrMEAN3.BeginInit();
            this.nrMEAN4.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.nrMEAN4.EndInit();
            this.nrMEAN3.EndInit();
            this.nrMEAN2.EndInit();
            this.nrMEAN1.EndInit();
            this.nrPRON4.EndInit();
            this.nrPRON3.EndInit();
            this.nrPRON2.EndInit();
            this.nrPRON1.EndInit();
            this.nrWORD4.EndInit();
            this.nrWORD3.EndInit();
            this.nrWORD2.EndInit();
            this.nrWORD1.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.nrWORD1 = Globals.Factory.CreateNamedRange(null, null, "nrWORD1", "nrWORD1", this);
            this.nrWORD2 = Globals.Factory.CreateNamedRange(null, null, "nrWORD2", "nrWORD2", this);
            this.nrWORD3 = Globals.Factory.CreateNamedRange(null, null, "nrWORD3", "nrWORD3", this);
            this.nrWORD4 = Globals.Factory.CreateNamedRange(null, null, "nrWORD4", "nrWORD4", this);
            this.nrPRON1 = Globals.Factory.CreateNamedRange(null, null, "nrPRON1", "nrPRON1", this);
            this.nrPRON2 = Globals.Factory.CreateNamedRange(null, null, "nrPRON2", "nrPRON2", this);
            this.nrPRON3 = Globals.Factory.CreateNamedRange(null, null, "nrPRON3", "nrPRON3", this);
            this.nrPRON4 = Globals.Factory.CreateNamedRange(null, null, "nrPRON4", "nrPRON4", this);
            this.nrMEAN1 = Globals.Factory.CreateNamedRange(null, null, "nrMEAN1", "nrMEAN1", this);
            this.nrMEAN2 = Globals.Factory.CreateNamedRange(null, null, "nrMEAN2", "nrMEAN2", this);
            this.nrMEAN3 = Globals.Factory.CreateNamedRange(null, null, "nrMEAN3", "nrMEAN3", this);
            this.nrMEAN4 = Globals.Factory.CreateNamedRange(null, null, "nrMEAN4", "nrMEAN4", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // nrWORD1
            // 
            this.nrWORD1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrWORD2
            // 
            this.nrWORD2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrWORD3
            // 
            this.nrWORD3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrWORD4
            // 
            this.nrWORD4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPRON1
            // 
            this.nrPRON1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPRON2
            // 
            this.nrPRON2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPRON3
            // 
            this.nrPRON3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPRON4
            // 
            this.nrPRON4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrMEAN1
            // 
            this.nrMEAN1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrMEAN2
            // 
            this.nrMEAN2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrMEAN3
            // 
            this.nrMEAN3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrMEAN4
            // 
            this.nrMEAN4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // EnWordsFormat
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.nrMEAN4.Dispose();
            this.nrMEAN3.Dispose();
            this.nrMEAN2.Dispose();
            this.nrMEAN1.Dispose();
            this.nrPRON4.Dispose();
            this.nrPRON3.Dispose();
            this.nrPRON2.Dispose();
            this.nrPRON1.Dispose();
            this.nrWORD4.Dispose();
            this.nrWORD3.Dispose();
            this.nrWORD2.Dispose();
            this.nrWORD1.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {

        private static EnWordsFormat _EnWordsFormat;

        internal static EnWordsFormat EnWordsFormat
        {
            get {
                return _EnWordsFormat;
            }
            set {
                if ((_EnWordsFormat == null))
                {
                    _EnWordsFormat = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
