//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExMyStudy {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(12)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Setting : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.ListObject lstGrade;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstTerm;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstModule;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstUnit;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstLevel;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstEnQType;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstCnQType;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstSubject;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstCnUnit;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstSxQType;
        
        internal Microsoft.Office.Tools.Excel.ListObject lstQType;
        
        internal Microsoft.Office.Tools.Excel.ListObject list1;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Setting(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet4", "Sheet4") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Setting = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.lstGrade.BeginInit();
            this.lstTerm.BeginInit();
            this.lstModule.BeginInit();
            this.lstUnit.BeginInit();
            this.lstLevel.BeginInit();
            this.lstEnQType.BeginInit();
            this.lstCnQType.BeginInit();
            this.lstSubject.BeginInit();
            this.lstCnUnit.BeginInit();
            this.lstSxQType.BeginInit();
            this.lstQType.BeginInit();
            this.list1.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.list1.EndInit();
            this.lstQType.EndInit();
            this.lstSxQType.EndInit();
            this.lstCnUnit.EndInit();
            this.lstSubject.EndInit();
            this.lstCnQType.EndInit();
            this.lstEnQType.EndInit();
            this.lstLevel.EndInit();
            this.lstUnit.EndInit();
            this.lstModule.EndInit();
            this.lstTerm.EndInit();
            this.lstGrade.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.lstGrade = Globals.Factory.CreateListObject(null, null, "Sheet4:lstGrade", "lstGrade", this);
            this.lstTerm = Globals.Factory.CreateListObject(null, null, "Sheet4:lstTerm", "lstTerm", this);
            this.lstModule = Globals.Factory.CreateListObject(null, null, "Sheet4:lstModule", "lstModule", this);
            this.lstUnit = Globals.Factory.CreateListObject(null, null, "Sheet4:lstUnit", "lstUnit", this);
            this.lstLevel = Globals.Factory.CreateListObject(null, null, "Sheet4:lstLevel", "lstLevel", this);
            this.lstEnQType = Globals.Factory.CreateListObject(null, null, "Sheet4:lstEnQType", "lstEnQType", this);
            this.lstCnQType = Globals.Factory.CreateListObject(null, null, "Sheet4:lstCnQType", "lstCnQType", this);
            this.lstSubject = Globals.Factory.CreateListObject(null, null, "Sheet4:lstSubject", "lstSubject", this);
            this.lstCnUnit = Globals.Factory.CreateListObject(null, null, "Sheet4:lstCnUnit", "lstCnUnit", this);
            this.lstSxQType = Globals.Factory.CreateListObject(null, null, "Sheet4:lstSxQType", "lstSxQType", this);
            this.lstQType = Globals.Factory.CreateListObject(null, null, "Sheet4:lstQType", "lstQType", this);
            this.list1 = Globals.Factory.CreateListObject(null, null, "Sheet4:list1", "list1", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // lstGrade
            // 
            this.lstGrade.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstTerm
            // 
            this.lstTerm.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstModule
            // 
            this.lstModule.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstUnit
            // 
            this.lstUnit.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstLevel
            // 
            this.lstLevel.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstEnQType
            // 
            this.lstEnQType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstCnQType
            // 
            this.lstCnQType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstSubject
            // 
            this.lstSubject.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstCnUnit
            // 
            this.lstCnUnit.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstSxQType
            // 
            this.lstSxQType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // lstQType
            // 
            this.lstQType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // list1
            // 
            this.list1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // Setting
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.list1.Dispose();
            this.lstQType.Dispose();
            this.lstSxQType.Dispose();
            this.lstCnUnit.Dispose();
            this.lstSubject.Dispose();
            this.lstCnQType.Dispose();
            this.lstEnQType.Dispose();
            this.lstLevel.Dispose();
            this.lstUnit.Dispose();
            this.lstModule.Dispose();
            this.lstTerm.Dispose();
            this.lstGrade.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Setting _Setting;
        
        internal static Setting Setting {
            get {
                return _Setting;
            }
            set {
                if ((_Setting == null)) {
                    _Setting = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
