//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExMyStudy {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(7)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class CnPhraseFormat : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY5;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE5;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY6;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE6;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY1;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPHRASE4;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY2;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY3;
        
        internal Microsoft.Office.Tools.Excel.NamedRange nrPINY4;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public CnPhraseFormat(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Sheet11", "Sheet11") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.CnPhraseFormat = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.nrPINY5.BeginInit();
            this.nrPHRASE5.BeginInit();
            this.nrPINY6.BeginInit();
            this.nrPHRASE6.BeginInit();
            this.nrPHRASE1.BeginInit();
            this.nrPINY1.BeginInit();
            this.nrPHRASE2.BeginInit();
            this.nrPHRASE3.BeginInit();
            this.nrPHRASE4.BeginInit();
            this.nrPINY2.BeginInit();
            this.nrPINY3.BeginInit();
            this.nrPINY4.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.nrPINY4.EndInit();
            this.nrPINY3.EndInit();
            this.nrPINY2.EndInit();
            this.nrPHRASE4.EndInit();
            this.nrPHRASE3.EndInit();
            this.nrPHRASE2.EndInit();
            this.nrPINY1.EndInit();
            this.nrPHRASE1.EndInit();
            this.nrPHRASE6.EndInit();
            this.nrPINY6.EndInit();
            this.nrPHRASE5.EndInit();
            this.nrPINY5.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.nrPINY5 = Globals.Factory.CreateNamedRange(null, null, "nrPINY5", "nrPINY5", this);
            this.nrPHRASE5 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE5", "nrPHRASE5", this);
            this.nrPINY6 = Globals.Factory.CreateNamedRange(null, null, "nrPINY6", "nrPINY6", this);
            this.nrPHRASE6 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE6", "nrPHRASE6", this);
            this.nrPHRASE1 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE1", "nrPHRASE1", this);
            this.nrPINY1 = Globals.Factory.CreateNamedRange(null, null, "nrPINY1", "nrPINY1", this);
            this.nrPHRASE2 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE2", "nrPHRASE2", this);
            this.nrPHRASE3 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE3", "nrPHRASE3", this);
            this.nrPHRASE4 = Globals.Factory.CreateNamedRange(null, null, "nrPHRASE4", "nrPHRASE4", this);
            this.nrPINY2 = Globals.Factory.CreateNamedRange(null, null, "nrPINY2", "nrPINY2", this);
            this.nrPINY3 = Globals.Factory.CreateNamedRange(null, null, "nrPINY3", "nrPINY3", this);
            this.nrPINY4 = Globals.Factory.CreateNamedRange(null, null, "nrPINY4", "nrPINY4", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // nrPINY5
            // 
            this.nrPINY5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE5
            // 
            this.nrPHRASE5.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPINY6
            // 
            this.nrPINY6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE6
            // 
            this.nrPHRASE6.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE1
            // 
            this.nrPHRASE1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPINY1
            // 
            this.nrPINY1.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE2
            // 
            this.nrPHRASE2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE3
            // 
            this.nrPHRASE3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPHRASE4
            // 
            this.nrPHRASE4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPINY2
            // 
            this.nrPINY2.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPINY3
            // 
            this.nrPINY3.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // nrPINY4
            // 
            this.nrPINY4.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never;
            // 
            // CnPhraseFormat
            // 
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "10.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.nrPINY4.Dispose();
            this.nrPINY3.Dispose();
            this.nrPINY2.Dispose();
            this.nrPHRASE4.Dispose();
            this.nrPHRASE3.Dispose();
            this.nrPHRASE2.Dispose();
            this.nrPINY1.Dispose();
            this.nrPHRASE1.Dispose();
            this.nrPHRASE6.Dispose();
            this.nrPINY6.Dispose();
            this.nrPHRASE5.Dispose();
            this.nrPINY5.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static CnPhraseFormat _CnPhraseFormat;
        
        internal static CnPhraseFormat CnPhraseFormat {
            get {
                return _CnPhraseFormat;
            }
            set {
                if ((_CnPhraseFormat == null)) {
                    _CnPhraseFormat = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
